# Generated by Django 5.2.8 on 2025-11-11 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('linea_naviera', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Buque',
            },
        ),
        migrations.CreateModel(
            name='CitaRecojo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_horario', models.DateField()),
                ('fecha_salida_horario', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cita_recojo',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('monto', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='NivelAcceso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Nivel_acceso',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_generacion', models.DateField()),
                ('parametros', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Reporte',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='UbicacionSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Ubicacion_slot',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'db_table': 'Zona',
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dimensiones', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('peso', models.FloatField()),
                ('id_buque', models.ForeignKey(db_column='id_buque', on_delete=django.db.models.deletion.CASCADE, to='core.buque')),
                ('id_cita_recojo', models.ForeignKey(db_column='id_cita_recojo', on_delete=django.db.models.deletion.CASCADE, to='core.citarecojo')),
            ],
            options={
                'db_table': 'Contenedor',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('medio_pago', models.CharField(max_length=30)),
                ('monto', models.FloatField()),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_entrada', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('id_contenedor', models.ForeignKey(db_column='id_contenedor', on_delete=django.db.models.deletion.CASCADE, to='core.contenedor')),
                ('id_ubicacion', models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.CASCADE, to='core.ubicacionslot')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='id_ticket',
            field=models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, to='core.ticket'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_nivel_acceso', models.ForeignKey(db_column='id_nivel_acceso', on_delete=django.db.models.deletion.CASCADE, to='core.nivelacceso')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='ubicacionslot',
            name='id_zona',
            field=models.ForeignKey(db_column='id_zona', on_delete=django.db.models.deletion.CASCADE, to='core.zona'),
        ),
    ]
