# Generated by Django 5.2.8 on 2025-11-12 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citarecojo',
            name='duracion_viaje_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citarecojo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='citarecojo',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citarecojo',
            name='fecha_recojo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citarecojo',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='citarecojo',
            name='estado',
            field=models.CharField(default='reservada', max_length=50),
        ),
        migrations.AlterField(
            model_name='citarecojo',
            name='fecha_inicio_horario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citarecojo',
            name='fecha_salida_horario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='id_cita_recojo',
            field=models.ForeignKey(blank=True, db_column='id_cita_recojo', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.citarecojo'),
        ),
    ]
