# Generated by Django 5.2.8 on 2025-11-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_citarecojo_duracion_viaje_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='numero_contenedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
